# Generated by Django 4.1.5 on 2023-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_delete_companyname_delete_date_delete_ic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(),
        ),
    ]
